apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluentd.configmap.fullname" .}}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "fluentd"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{ toYaml .Values.configFiles | indent 2 }}