apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluentd.configmap.fullname" .}}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ toYaml .Values.configFiles | indent 2 }}