apiVersion: v1
description: Kibana analytics and search dashboard for Elasticsearch
name: kibana
version: 0.1.0
maintainers:
  - name: Alexander Brand
    email: abrand@apprenda.com
  - name: Dimitri Koshkin
    email: dkoshkin@apprenda.com
