apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default (include "elasticsearch.service.fullname" .) }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.name | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: client
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: {{ .Values.name | quote }}
    release: {{ .Release.Name | quote }}
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
