apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.name | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  type: {{ .Values.serviceType | quote }}
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    app: {{ template "kibana.name" . }}
    component: {{ .Values.name | quote }}
    release: {{ .Release.Name | quote }}