apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.data.service.fullname" . }} 
  labels:
    app: {{ template "kismatic-logging-efk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.elasticsearch.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    app: {{ template "kismatic-logging-efk.name" . }}
    component: {{ .Values.elasticsearch.name }}
    role: data