apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.service.fullname" . }}
  labels:
    app: {{ template "kismatic-logging-efk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.elasticsearch.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    role: client
spec:
  type: {{ .Values.elasticsearch.serviceType }}
  selector:
    app: {{ template "kismatic-logging-efk.name" . }}
    component: {{ .Values.elasticsearch.name }}
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
