apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app: {{ template "kismatic-logging-efk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.fluentd.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: {{ template "kismatic-logging-efk.name" . }}
        component: {{ .Values.fluentd.name }}
        release: {{ .Release.Name }}
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd
        image: {{ .Values.fluentd.image }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "{{ template "elasticsearch.service.fullname" . }}"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: {{ template "fluentd.configmap.fullname" .}}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
