apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.service.fullname" . }}
  labels:
    app: {{ template "kismatic-logging-efk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.kibana.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  type: {{ .Values.kibana.serviceType }}
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    app: {{ template "kismatic-logging-efk.name" . }}
    component: {{ .Values.kibana.name }}