apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app: {{ template "kismatic-logging-efk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.kibana.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  replicas: {{ .Values.kibana.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "kismatic-logging-efk.name" . }}
        component: {{ .Values.kibana.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: kibana-logging
        image: {{ .Values.kibana.image }}
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://{{ template "elasticsearch.service.fullname" . }}:9200"
          - name: "KIBANA_BASE_URL"
            value: "/api/v1/proxy/namespaces/kube-system/services/kibana-logging"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP